spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-N0RVHB7; databasename=hebotest;
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
server:
  port: 8082
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG